YouTubeLearn/Display/urls.py
from django.urls import path
from Display.views import show_video
from Display.views import send_api_key
from Display.views import create_models
from Display.views import home
from Display.views import playlist                                                                      
from Display.views import delete_playlist
from Display.views import delete_video
from Display.views import add_text

app_name = 'Display'

urlpatterns  = [
    path('videos/<path:name>/', show_video, name='show_video'),
    path('send_api_key/', send_api_key, name='send_api_key'),
    path('create_models/', create_models, name='create_models'),
    path('', home, name='home'),
    path('playlist/<str:name>/', playlist, name='show_playlist'),
    path('delete_playlist/<path:name>/', delete_playlist, name='delete_playlist'),
    path('delete_video/<path:name>/', delete_video, name='delete_video'),
    path('add_text/', add_text, name='add_text'),
    
]

YouTubeLearn/YouTubeLearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Display.urls'), name='Display'),
]

YouTubeLearn/Display/models.py
from googleapiclient.discovery import build
from django.db import models

from decouple import Config, RepositoryEnv

import random
import string
from ckeditor.fields import RichTextField

config = Config(RepositoryEnv('.env'))
api_key = config('API_KEY')


class Video(models.Model):
    url = models.URLField()
    thumbnail = models.URLField(null=True, blank=True)  # Add the thumbnail field
    name = models.CharField(max_length=200, null=True, blank=True)  # Add the name field
    _inherited = models.BooleanField(default=False)
    words = RichTextField(default='')  # Add the words field

    def save(self, *args, **kwargs):
        video_id = self.url.split('=')[1]
        if '&' in video_id:
            video_id = video_id.split('&')[0]
        self.thumbnail = get_video_thumbnail(video_id)  # Set the thumbnail before saving
        self.name = get_video_name(video_id) # Set the name before saving
        super().save(*args, **kwargs)
        
    @property
    def model_name(self):
        return 'Video'

    def __str__(self):
        return self.url


class Playlist(models.Model):
    url = models.URLField()
    thumbnail = models.URLField(null=True, blank=True)  # Add the thumbnail field
    name = models.CharField(max_length=200, null=True, blank=True)  # Add the name field
    videos = models.ManyToManyField(Video, related_name='playlists')  # Add the videos field

    def save(self, *args, **kwargs):
        playlist_id = self.url.split('=')[1]
        # convert_playlist_to_videos(playlist_id)
        self.thumbnail = get_playlist_thumbnail(playlist_id)
        self.name = get_playlist_name(playlist_id)
        super().save(*args, **kwargs)  # Save the Playlist instance to the database
        self.videos.set(get_videos(playlist_id, self))  # Set the many-to-many relationship



    @property
    def model_name(self):
        return 'Playlist'
    
    def __str__(self):
        return self.url

def get_playlist_thumbnail(playlist_id):
    # Use the YouTube Data API client to retrieve the playlist thumbnail
    youtube = build('youtube', 'v3', developerKey=api_key)
    request = youtube.playlists().list(
        part='snippet',
        id=playlist_id
    )
    response = request.execute()

    # Extract the playlist thumbnail URL from the response
    if 'items' in response and len(response['items']) > 0:
        playlist_snippet = response['items'][0]['snippet']
        if 'thumbnails' in playlist_snippet:
            thumbnails = playlist_snippet['thumbnails']
            if 'medium' in thumbnails:
                return thumbnails['medium']['url']

    return None


def get_video_thumbnail(video_id):
    # Use the YouTube Data API client to retrieve the video thumbnail
    youtube = build('youtube', 'v3', developerKey=api_key)
    request = youtube.videos().list(
        part='snippet',
        id=video_id
    )
    response = request.execute()

    # Extract the video thumbnail URL from the response
    if 'items' in response and len(response['items']) > 0:
        video_snippet = response['items'][0]['snippet']
        if 'thumbnails' in video_snippet:
            thumbnails = video_snippet['thumbnails']
            if 'medium' in thumbnails:
                return thumbnails['medium']['url']

    return None

def get_video_name(video_id):
    # Use the YouTube Data API client to retrieve the video name
    youtube = build('youtube', 'v3', developerKey=api_key)
    request = youtube.videos().list(
        part='snippet',
        id=video_id
    )
    response = request.execute()

    # Extract the video name from the response
    if 'items' in response and len(response['items']) > 0:
        video_snippet = response['items'][0]['snippet']
        if 'title' in video_snippet:
            return video_snippet['title']

    return random.choice(string.ascii_letters)

def get_video_response(video_id):
        # Use the YouTube Data API client to retrieve the video name
    youtube = build('youtube', 'v3', developerKey=api_key)
    request = youtube.videos().list(
        part='snippet',
        id=video_id
    )
    response = request.execute()
    response = response['items']
    return response

def get_playlist_name(playlist_id):
    # Use the YouTube Data API client to retrieve the playlist name
    youtube = build('youtube', 'v3', developerKey=api_key)
    request = youtube.playlists().list(
        part='snippet',
        id=playlist_id
    )
    response = request.execute()

    # Extract the playlist name from the response
    if 'items' in response and len(response['items']) > 0:
        playlist_snippet = response['items'][0]['snippet']
        if 'title' in playlist_snippet:
            return playlist_snippet['title']

    return random.choice(string.ascii_letters)

def get_videos(playlist_id, playlist):
    # Set up the YouTube Data API client
    youtube = build('youtube', 'v3', developerKey=api_key)

    # Retrieve the playlist items
    playlist_items = []
    next_page_token = None
    while True:
        request = youtube.playlistItems().list(
            part='contentDetails',
            playlistId=playlist_id,
            maxResults=50,
            pageToken=next_page_token
        )
        response = request.execute()

        playlist_items.extend(response['items'])
        next_page_token = response.get('nextPageToken')

        if not next_page_token:
            break


    for item in playlist_items:
        video_id = item['contentDetails']['videoId']
        video_url = f'https://www.youtube.com/watch?v={video_id}'
        video = Video.objects.create(name=get_video_name(video_id), thumbnail=get_video_thumbnail(video_id)
                                           , url=video_url, _inherited=True)
        playlist.videos.add(video)
        
    return playlist.videos.all()

YouTubeLearn/Display/forms.py
from django import forms
from .models import Video, Playlist
from django.forms import ModelForm

class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = '__all__'
        
class PlaylistForm(ModelForm):
    class Meta:
        model = Playlist
        fields = '__all__'

YouTubeLearn/Display/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from decouple import Config, RepositoryEnv
from Display.models import Video, Playlist

config = Config(RepositoryEnv('.env'))
api_key = config('API_KEY')
                  

def show_video(request, name):
    try:
        video = Video.objects.get(name=name)
        video_id = video.url.split('=')[1]  # Extract the video ID from the URL#  
        if '&' in video_id:
            video_id = video.url.split('&')[0] 
        print(video.words)
        context = {
            'video_id': video_id,
            'name': name,
            'words': video.words,
        }
        print(video.words)
        return render(request, 'Display/youtube.html', context)
    except Video.DoesNotExist:
        print('Video does not exist')
        return redirect('Display:home')
    except Video.MultipleObjectsReturned:
        print('Multiple videos returned')
        return redirect('Display:home')
    except:
        print('Something else went wrong')
        return redirect('Display:home')


def send_api_key(request):
    if request.method == 'GET':
        return JsonResponse({'api_key_response': api_key})
    
def home(request):
    videos = Video.objects.exclude(_inherited=True)[:10]
    playlists = Playlist.objects.all()[:10]

    context = {
        'videos': videos,
        'playlists': playlists,
    }

    return render(request, 'Display/youhome.html', context)
    
def create_models(request):
    if request.method == 'POST':
        url = request.POST.get('url')
        if url:
            if url in [video.url for video in Video.objects.all()]:
                return redirect('Display:home')
            if url in [playlist.url for playlist in Playlist.objects.all()]:
                return redirect('Display:home')
            # Check if the URL is for a video or a playlist
            if 'youtube.com/playlist' in url:
                # Create Playlist model
                playlist = Playlist(url=url)
                playlist.save()
            elif 'youtube.com/watch' in url:
                # Create Video model
                video = Video(url=url)
                video.save()
                if video.name == None:
                    video.name = video.url.split('=')[1]
                    return redirect('Display:home')

    # Redirect back to the same page after creating the models
    return redirect('Display:home')


def playlist(request, name):
    playlist = Playlist.objects.get(name=name)
    return render(request, 'Display/youplaylist.html', {'playlist': playlist}) 


def delete_video(request, name):
    if request.method == 'POST':
        video = Video.objects.get(name=name)
        video.delete()
        return redirect('Display:home')
    else:
        return redirect('Display:home')
    
def delete_playlist(request, name):
    if request.method == 'POST':
        playlist = Playlist.objects.get(name=name)
        playlist.delete()
        return redirect('Display:home')
    else:
        return redirect('Display:home')
    

def add_text(request):
    if request.method == 'POST':
        print('message received')
        text = request.POST.get('text')
        name = request.POST.get('name')
        video = Video.objects.get(name=name)
        video.words = text
        print(video.words)
        video.save()
        return redirect('Display:show_video', name=name)
    else:
        return redirect('Display:show_video', name=name)

YouTubeLearn/Display/templates/Display/youbase.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}YouTube Study{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />      
    {% load static %}
    <link rel="stylesheet" href="{% static 'Display/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel='icon' href="{% static 'img/YouFav.ico' %}" type='image/x-icon'/ >
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <div class='youtube-title'>
        <script>
            function goBackToHomePage() {
                window.location.href = "{% url 'Display:home' %}";
           }
        </script>
        <h1 class='primaryHeader' onclick='goBackToHomePage()'>YouTube Study Mode</h1>
    </div>
    {% block content %}
    {% endblock %}


YouTubeLearn/Display/templates/Display/youhome.html
{% extends 'Display/youbase.html' %}

{% block content %}

{% block head %}
{% load static %}

{% endblock %}

{% block body %}
<script>
    function gotoVideo(videoUrl) {
            window.location.href = videoUrl;    
    }
    function gotoPlaylist(playlistUrl) {
        window.location.href = playlistUrl;
    }
</script>
<div class="container">
    <form method="POST" action="{% url 'Display:create_models' %}">
        {% csrf_token %}
        <input type="text" name="url" id="urlInput" placeholder="Enter YouTube URL">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <button type="submit" class="btn btn-danger" onclick="showSpinner()">Submit</button>
    </form>
    <div class="spinner-border text-danger" style="display: none;" role="status" id="spinner">
        <span class="visually-hidden">Loading...</span>
    </div>
    <script>
        function showSpinner() {
            document.getElementById("spinner").style.display = "block";
        }
    </script>

    <h2>Videos</h2>
    <div class="row justify-content-center">
        <div class="col-md-10">
          <div class="videos-and-playlists">
            <div class="scrollable-row{% if videos|length > 2 %} overflow-auto{% endif %} d-flex flex-row flex-nowrap">
              {% for video in videos %}
              <div class="video-item">
                <p class="video-name" onclick="gotoVideo('{% url 'Display:show_video' video.name %}')">{{ video.name }}</p>
                <img src="{{ video.thumbnail }}" alt="thumbnail">
                <form method="POST" action="{% url 'Display:delete_video' video.name %}">
                  {% csrf_token %}
                  <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      
      
      <h2>Playlists</h2>
        <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="videos-and-playlists">
            <div class="scrollable-row{% if playlists|length > 2 %} overflow-auto{% endif %} d-flex flex-row flex-nowrap">
                {% for playlist in playlists %}
                <div class="playlist-item">
                    <p class="playlist-name" data-max-length="45" onclick="gotoPlaylist('{%url 'Display:show_playlist' playlist.name%}')">{{ playlist.name }}</p>
                <img src="{{ playlist.thumbnail }}" alt="thumbnail" style="margin-right: 10px">
                <form method="POST" action="{% url 'Display:delete_playlist' playlist.name %}">
                    {% csrf_token %}
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
                {% endfor %}
            </div>
            </div>
        </div>
        </div>
        <script>
            // Truncate playlist names based on the specified maximum length
            const playlistNames = document.querySelectorAll('.playlist-name');
            playlistNames.forEach(name => {
              const maxLength = parseInt(name.dataset.maxLength, 10);
              const text = name.textContent;
              if (text.length > maxLength) {
                name.textContent = text.slice(0, maxLength) + '...';
              }
            });
          </script>
          

</div>
{% endblock %}
{% endblock %}


YouTubeLearn/Display/templates/Display/youplaylist.html
{% extends 'Display/youbase.html' %}
{% block content %}
    <div class="playlists">
        <h1>{{ playlist.name }}</h1>
        <script>
            function gotoVideo(videoUrl){
                window.location.href = videoUrl;
            }
        </script>
        {% for video in playlist.videos.all %}
            <div class='playlist-videos'>
                <p class="video-name" onclick="gotoVideo('{% url 'Display:show_video' video.name %}')">{{ video.name }}</p>
                <img src="{{ video.thumbnail }}" alt="thumbnail">
            </div>
        {% endfor %}
    </div>
{% endblock %}


YouTubeLearn/Display/templates/Display/youtube.html
{% extends 'Display/youbase.html' %}
{% block content %}
{% block head %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://www.youtube.com/iframe_api"></script>
<script src="https://cdn.tiny.cloud/1/2mtv3gujo2i5ds70e7k2t0jzbjwraerdlhhywnqqdrtmnnpt/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.min.js" integrity="sha512-Qsh05D07P6dURSZn8Qk+j8GI7cEK0OhXleZvTofmucwoDSkBC0juWf1401JdSE8os2kWEezMu7e9mlnszm3yEw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.min.css" integrity="sha512-/MlSi6MBnEjKBuoY+vWZE8slTPRlkaKiE46RE0L1jQHodl48ndAOjkVB0GKXHwVmbQhpnVdCTzsjoDGgkbUjyg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% load static %}
<script src="{% static 'Display/functions.js' %}"></script>
</head>
{% endblock %}
{% block body %}
<script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue + '; SameSite=None; Secure'; // add the SameSite and Secure attributes
  }


document.addEventListener('DOMContentLoaded', function() {
  ajaxRequest('GET', '/send_api_key/', null, 'json', function(error, response) {
    if (error) {
      console.error('Error:', error);
    } else {
      console.log('success');
      // Use the API key as needed
      let api_key = response.api_key_response;
      loadYouTubeAPI(api_key); // Pass the API key to the loadYouTubeAPI function
    }
  });
});

function sendText() {

  var text = tinymce.get('textarea').getContent();
  var name = '{{ name }}';
  var data = {
    'text': text,
    'name': name,
    'csrfmiddlewaretoken': "{{ csrf_token }}"
  };
  

  ajaxRequest('POST', '/add_text/', data, null, function(error, response) {
    if (error) {
      console.error('Error:', error);
    } else {
      console.log(text);
      console.log('text success');
    }
  });
}

function onPlayerReady(event) {
  event.target.cueVideoById({
    videoId: "{{video_id}}", // Replace with your video ID
    startSeconds: 0, // Start playing from the beginning
    suggestedQuality: 'hd720' // You can set the suggested quality for playback
  });
}

// Load the YouTube API asynchronously
function loadYouTubeAPI(api_key) {
  var tag = document.createElement('script');
  tag.src = 'https://www.youtube.com/iframe_api?apikey=' + api_key;
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
}

// Once the YouTube API script is loaded, execute your code
function onYouTubeIframeAPIReady() {
  var screenWidth = window.innerWidth; // Get the width of the screen
  var screenHeight = window.innerHeight; // Get the height of the screen
  var playerWidth = screenWidth * 0.8; // Set the width of the player to 80% of the screen width
  var playerHeight = screenHeight * 0.6; // Set the height of the player to 80% of the screen height

  new YT.Player('player', {
    height: playerHeight,
    width: playerWidth,
    videoId: "{{video_id}}", // Replace with your video ID
    events: {
      'onReady': onPlayerReady
    }
  });
}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js"></script>
<script>
  // Check if MathQuill has been loaded
  if (typeof MQ !== 'undefined') {
    // MathQuill is loaded
    console.log('MathQuill is loaded.');
    // You can proceed with your code that depends on MathQuill
  } else {
    // MathQuill is not loaded
    console.log('MathQuill is not loaded yet.');
    // You can handle the error or try loading MathQuill again
  }

  // Alternatively, you can use the window.onload event or DOMContentLoaded event
  window.onload = function() {
    // MathQuill is loaded
    console.log('MathQuill is loaded.');
    // You can proceed with your code that depends on MathQuill
  };
</script>
    <div class='main-area'>
      <div id="player"></div>
      <div class='text-editor'>
      <textarea id='textarea'>
        \sqrt{3x+1} + (1+x)^2
        {{words}}
      </textarea>
      <div class='buttons'>
        {%csrf_token%}
          <button class='btn btn-danger' onclick="sendText()" style="margin-left:30px;">Save</button>
        <button onclick="saveAsWord('{{name}}')" class='btn btn-danger'>Save as Word</button>
      </div>
    </div>


    <script>

      function initializeMathQuill() {
        var textarea = document.getElementById('textarea');
        var mathField = MQ.MathField(textarea, {
          spaceBehavesLikeTab: true,
          handlers: {
            edit: function() {
              console.log(mathField.latex());
            }
          }
        });
        
        mathField.latex('2^{\\frac{3}{2}}');
        mathField.latex(textarea.value);
    
        // Additional code or actions that depend on MathQuill
        console.log('MathQuill is loaded.');
      }

      function loadMathQuill() {
        // Check if MathQuill has been loaded
        if (typeof MQ !== 'undefined') {
          // MathQuill is already loaded
          initializeMathQuill();
        } else {
          // MathQuill is not loaded, wait for it to load
          document.addEventListener('mathquill:loaded', initializeMathQuill);
        }
      }
    
      // Your existing code...
    
      // Call the loadMathQuill() function
      loadMathQuill();

    

      tinymce.init({
        selector: 'textarea',
        plugins: 'lists advlist autolink autosave code emoticons image link media pagebreak preview save searchreplace table visualblocks wordcount latex',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        mergetags_list: [
          { value: 'First.Name', title: 'First Name' },
          { value: 'Email', title: 'Email' },
        ],
      });

      function saveAsWord(filename) {
        var textareaContent = tinymce.get('textarea').getContent().replace(/<[^>]*>/g, ""); // Get the HTML content from TinyMCE
        // Create a new Blob object with the HTML content
        var blob = new Blob([textareaContent], { type: 'application/msword' });
        filename = filename.replace(/ /g, "_");
        filename = filename.replace(/:/g, "");
        // Use the FileSaver.js library to save the Blob as a Word document
        saveAs(blob, filename + '.doc');
      }
      
    </script>
</body>
{%endblock%}
{%endblock%}